<?php

namespace Colmenapp\PlataformaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ColmenaInspeccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColmenaInspeccionRepository extends EntityRepository
{
}
