apiario:
    path:     /
    defaults: { _controller: ColmenappPlataformaBundle:Apiario:index, _name: apiario }
    methods:  GET

apiario_detalle:
    path:     /detalle
    defaults: { _controller: "ColmenappPlataformaBundle:Apiario:detalle" }
    methods:  GET