colmena:
    path:     /
    defaults: { _controller: "ColmenappPlataformaBundle:Colmena:index", _name: colmena  }
    methods:  GET

colmena_inspeccion:
    path:     /inspeccion
    defaults: { _controller: "ColmenappPlataformaBundle:Colmena:inspeccion" }
    methods:  GET

colmena_inspeccion_nueva:
    path:     /inspeccion-nueva
    defaults: { _controller: "ColmenappPlataformaBundle:Colmena:inspeccionNueva", _name: colmena  }
    methods:  GET

colmena_detalle:
    path:     /detalle
    defaults: { _controller: "ColmenappPlataformaBundle:Colmena:detalle", _name: colmena , _name: colmena  }
    methods:  GET