colmena:
    path:     /
    defaults: { _controller: "ColmenappPlataformaBundle:Colmena:index", _name: colmena  }
    methods:  GET

colmena_inspeccion:
    path:     /inspeccion
    defaults: { _controller: "ColmenappPlataformaBundle:Colmena:inspeccion" }
    methods:  GET

colmena_inspeccion_nueva:
    path:     /inspeccion-nueva
    defaults: { _controller: "ColmenappPlataformaBundle:Colmena:inspeccionNueva", _name: colmena  }
    methods:  GET

colmena_detalle:
    path:     /detalle/{id}
    defaults: { _controller: "ColmenappPlataformaBundle:Colmena:detalle" }
    methods:  GET

colmena_crear:
    path:     /crear
    defaults: { _controller: "ColmenappPlataformaBundle:Colmena:crear" }
    methods:  POST
    options:
            expose: true

colmenas:
    path:     /colmenas/{apiarioId}
    defaults: { _controller: "ColmenappPlataformaBundle:Colmena:getColmenas" }
    methods:  GET
    options:
            expose: true

colmenas_tipos:
    path:     /tipos-colmenas
    defaults: { _controller: "ColmenappPlataformaBundle:Colmena:getTiposColmenas" }
    methods:  GET
    options:
            expose: true

colmena_editar:
    path:     /editar
    defaults: { _controller: "ColmenappPlataformaBundle:Colmena:editar" }
    methods:  POST
    options:
            expose: true


