colmenapp_plataforma_homepage:
    path:     /
    defaults: { _controller: ColmenappPlataformaBundle:Dashboard:index }

periodo_produccion:
    resource: "@ColmenappPlataformaBundle/Resources/config/routing/periodoProduccion.yml"
    prefix:   /periodo-produccion
