colmenapp_plataforma_homepage:
    path:     /
    defaults: { _controller: ColmenappPlataformaBundle:Dashboard:index, _name: home }

periodo_produccion:
    resource: "@ColmenappPlataformaBundle/Resources/config/routing/periodoProduccion.yml"
    prefix:   /periodo-produccion

colmena:
    resource: "@ColmenappPlataformaBundle/Resources/config/routing/colmena.yml"
    prefix:   /colmena

apiario:
    resource: "@ColmenappPlataformaBundle/Resources/config/routing/apiario.yml"
    prefix:   /apiario

finanza:
    resource: "@ColmenappPlataformaBundle/Resources/config/routing/finanza.yml"
    prefix:   /finanza

alerta:
    resource: "@ColmenappPlataformaBundle/Resources/config/routing/alerta.yml"
    prefix:   /alerta

alimentacion:
    resource: "@ColmenappPlataformaBundle/Resources/config/routing/alimentacion.yml"
    prefix:   /alimentacion

tratamiento:
    resource: "@ColmenappPlataformaBundle/Resources/config/routing/tratamiento.yml"
    prefix:   /tratamiento

nucleo:
    resource: "@ColmenappPlataformaBundle/Resources/config/routing/nucleo.yml"
    prefix:   /nucleo

produccion:
    resource: "@ColmenappPlataformaBundle/Resources/config/routing/produccion.yml"
    prefix:   /produccion